### 0. Generate auth token
GET http://artem:159357Qq@192.168.0.199:8111/authenticationTest.html?csrf
Accept: application/json

### 1. Create project
POST http://artem:159357Qq@192.168.0.199:8111/app/rest/projects
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: e3f665af-5f9e-428b-bf05-a44f95658695

{
  "parentProject": {
    "locator": "_Root"
  },
  "name": "name",
  "id": "id",
  "copyAllAssociatedSettings": true
}
### 2. Create build configuration
POST http://artem:159357Qq@192.168.0.199:8111/app/rest/buildTypes
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: e1d12b02-39f3-4c00-82de-e28033280ea9

{
  "id": "id",
  "name": "Print hello world",
  "project": {
    "id": "id"
  },
  "parameters": {
    "property": [
      {
        "name": "myBuildParameter",
        "value": "myValue"
      }
    ]
  },
  "steps": {
    "step": [
      {
        "name": "Print hello world",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}

### 3. Run build configuration
POST http://artem:159357Qq@192.168.0.199:8111/app/rest/buildQueue
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: e1d12b02-39f3-4c00-82de-e28033280ea9

{
  "buildType": {
    "id": "id"
  }
}

### 4. Check build status
GET http://artem:159357Qq@192.168.0.199:8111/app/rest/builds/id:102
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: cec93d0a-38a8-4e05-a659-0b5e82f76ab6


###
